# Generated by Django 4.2.1 on 2023-07-23 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_post_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoContestSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('submitted', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(help_text='Image submitted for the photo contest', upload_to='')),
            ],
            options={
                'ordering': ['-submitted'],
            },
        ),
    ]
